version: '2'

services:
  mysql-vis:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 3s
      timeout: 1s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: vis
      MYSQL_USER: mysql
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    networks:
      - vis

  adminer-vis:
    image: adminer
    restart: always
    ports:
      - 9200:8080
    networks:
      - vis
    depends_on:
      mysql-vis:
        condition: service_healthy

  visapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - vis
    ports:
      - 8081:8081
    environment:
      MYSQL_HOST: mysql-vis
      MYSQL_PORT: 3306
    depends_on:
      mysql-vis:
        condition: service_healthy

networks:
  vis:
    external:
      name: vis_test